### ISSUE TITLE
Analytics Location filter fails with System.ArgumentException: Value does not fall within the expected range

### ISSUE THREAD

**Issue by mrdavidlaing** [fandrei/AppMetrics#119]
The following query began failing sometime in the last 2 days

```
http://analytics.metrics.labs.cityindex.com/GetReport.ashx?Application=CIAPILatencyCollector&Period=0:10:0&SliceByFunctions=Yes&FunctionFilter=CIAPI.Trade&Locations=Ireland
```

with error:

```
System.ArgumentException: Value does not fall within the expected range.
   at AppMetrics.AnalyticsSite.GetReport.CreateReport(AnalysisOptions options) in c:\dev\workspace\AppMetrics\AppMetrics.AnalyticsSite\GetReport.ashx.cs:line 158
   at AppMetrics.AnalyticsSite.GetReport.ProcessRequest(HttpContext context) in c:\dev\workspace\AppMetrics\AppMetrics.AnalyticsSite\GetReport.ashx.cs:line 35
```

The is the query that the current Solarwinds reports are using.  The intention is to get the measurements for just the Trade service from the Ireland node.

**Comment by fandrei** [comment]
Add this parameter:
&SliceByLocation=Countries

**Comment by mrdavidlaing** [comment]
Sweet, thanks.
