### ISSUE TITLE
Analytics reports fail if 127.0.0.1 logged as client IP

### ISSUE THREAD

**Issue by mrdavidlaing** [fandrei/AppMetrics#87]
If a test session contains the following logs:

```
  2012-06-26 15:50:59.0527220   ClientIP    127.0.0.1
  2012-06-26 15:50:59.0527220   ClientHostName  127.0.0.1
  2012-06-26 15:50:59.0527220   ClientUserAgent Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0)
  2012-06-26 15:50:59.0527220   Latency TestMethod  0.2
```

Then trying to pull an analytics report - http://analytics.metrics.labs.cityindex.com/GetReport.ashx?Application=test&Period=7.0:0:0&Type=LatencySummaries -  fails with:

```
 System.NullReferenceException: Object reference not set to an instance of an object.
 at AppMetrics.Analytics.StatsBuilder.<CalculateByCountries>b__1(SessionEx session) in   c:\dev\workspace\AppMetrics\AppMetrics.Analytics\StatsBuilder.cs:line 46
 at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
 at System.Linq.GroupedEnumerable`3.GetEnumerator()
 at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
 at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
 at AppMetrics.Analytics.Util.GroupBySorted[TSource,TKey](IEnumerable`1 source, Func`2 keySelector) in c:\dev\workspace\AppMetrics\AppMetrics.Analytics\Util.cs:line 53
 at AppMetrics.Analytics.StatsBuilder.CalculateByCountries() in c:\dev\workspace\AppMetrics\AppMetrics.Analytics\StatsBuilder.cs:line 46
 at AppMetrics.AnalyticsSite.GetReport.CreateReport(AnalysisOptions options) in c:\dev\workspace\AppMetrics\AppMetrics.AnalyticsSite\GetReport.ashx.cs:line 189
 at AppMetrics.AnalyticsSite.GetReport.GetOrCreateReport(AnalysisOptions options) in c:\dev\workspace\AppMetrics\AppMetrics.AnalyticsSite\GetReport.ashx.cs:line 143
 at AppMetrics.AnalyticsSite.GetReport.ProcessRequest(HttpContext context) in c:\dev\workspace\AppMetrics\AppMetrics.AnalyticsSite\GetReport.ashx.cs:line 29
```

**Comment by mrdavidlaing** [comment]
This kind of data happens if you submit test data from the server itself.

Its quite an edge case, so it might not be worth fixing.
